name: Build SDL
on:
  push:
    tags:
      - '*'
jobs:
  Build-Release:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./download-sdl.sh
      - run: mkdir -p tmp/bin tmp/include tmp/lib tmp/licenses
      - run: ./zlib.sh
      - run: ./libpng.sh
      - run: ./SDL2.sh
      - run: ./SDL2_image.sh
      - run: ./SDL2_mixer.sh
      - run: ./pack-sdl.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/SDL-x86_64-w64-mingw32.tgz
          asset_name: SDL-x86_64-w64-mingw32.tgz
          tag: ${{ github.ref }}
          overwrite: true
