name: Build Release
on:
  push:
    tags:
      - '*'
jobs:
  Build-Release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./download.sh
      - run: ./make.sh
      - run: ./pack.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: SDL-x86_64-w64-mingw32.tgz
          asset_name: SDL-x86_64-w64-mingw32.tgz
          tag: ${{ github.ref }}
          overwrite: true
